# nginx
nginx:
  image: nginx:alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - /data/www/taxi:/usr/share/nginx/html
    - ./nginx/logs:/var/log/nginx
  links:
    - php

# php
php:
  build: ./php
  ports:
    - "9000"
  volumes:
    - ./php/logs:/var/log
    - /data/www/taxi:/usr/share/nginx/html



