nginx:
  build: ./app/nginx
  ports:
    - "80:80"
    - "443:443"
  environment:
   - NGINX_HOST=blog.golune.com
   - NGINX_PORT=80
  volumes:
    # app
    - ./app/staff:/data/staff
    - ./app/chca:/data/chca
    - ./www:/data/www
    - ./app/nginx/logs:/var/log/nginx
    volumes_from:
    - chca

chca:
    build: ./app/chca
    ports: 
      - "9900:9900"
    

